// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moviebase.DAL;

#nullable disable

namespace Moviebase.DAL.Migrations
{
    [DbContext(typeof(MoviebaseDbContext))]
    partial class MoviebaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Moviebase.DAL.TestItem", b =>
                {
                    b.Property<int>("TestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("TestItemId");

                    b.ToTable("TestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
